services:
  greenhouse:
    build: .
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    volumes:
      - .:/app
      - /mnt/SSD240-DRIVE/projects/media/greenhouse/:/app/media/
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
