# Generated by Django 5.2.1 on 2025-05-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Plant's name")),
                ('last_water', models.DateTimeField()),
                ('next_water', models.DateField()),
            ],
        ),
    ]
