# Generated by Django 5.2.1 on 2025-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to="plant's_image/"),
        ),
        migrations.AddField(
            model_name='plants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
